[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.33.0"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
# CI backends to support
ci = "github"
# Where to host releases
hosting = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-unknown-linux-gnu", "arm-unknown-linux-gnueabihf", "x86_64-unknown-linux-gnu"]
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# Checksums to generate for each App
checksum = "sha256"
# Which actions to run on pull requests
pr-run-mode = "upload"
github-build-setup = "../release-setup.yml"
plan-jobs = ["./tests"]
global-artifacts-jobs = ["./release-check"]
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["NOTICE"]

[dist.github-custom-runners]
global = "ubuntu-24.04"
arm-unknown-linux-gnueabihf = "ubuntu-24.04"
aarch64-unknown-linux-gnu = "ubuntu-24.04-arm"
x86_64-unknown-linux-gnu = "ubuntu-24.04"

[dist.github-action-commits]
"actions/checkout" = "d23441a48e516b6c34aea4fa41551a30e30af803"
"actions/upload-artifact" = "ea165f8d65b6e75b540449e92b4886f43607fa02"
"actions/download-artifact" = "634f93cb2916e3fdff6788551b99b062d0335ce0"
